version: "0.2"
language: en
caseSensitive: false
allowCompoundWords: false
useGitignore: true
ignorePaths:
  - "**/{cspell.*,cSpell.*,.cspell.*,cspell.config.*}"
  - "**/node_modules/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/.vscode/**"
  - pnpm-lock.yaml
  - package-lock.json
  - "*.svg"
words:
  - autorun
  - catppuccin
  - disqus
  - domcontentloaded
  - Fira
  - fontsource
  - frontmatter
  - Giscus
  - jing
  - Katex
  - kebabcase
  - lhci
  - lighthouseci
  - microflash
  - noopener
  - noreferrer
  - Noto
  - pagefind
  - playform
  - rehype
  - seonaut
  - Tabler
  - tocbot
  - zite
