# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json
# https://prettier.io/docs/options

printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
jsxSingleQuote: false
trailingComma: all
bracketSameLine: false
arrowParens: always
endOfLine: lf
overrides:
  - files: "*.jsonc"
    options:
      trailingComma: none
plugins:
  - prettier-plugin-astro # https://github.com/withastro/prettier-plugin-astro
