# Header
menu:
  Home: /
  # Serial: /pages/serial
  Archives: /archives
  About: /pages/about.html
# rss: /atom.xml # Unuse RSS.

# Content
excerpt_link: 繼續閱讀
fancybox: true

# Sidebar
sidebar: Right
widgets:
- author
- tag
- category
# - archive
# - questionnaire
# - license

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
