# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Puppet"
license = "Apache"
licenselink = "https://github.com/roninro/hugo-theme-puppet/blob/master/LICENSE"
description = "a simple and clean theme for Hugo"
homepage = "https://github.com/roninro/hugo-theme-puppet"
# If you have a running demo of the theme.
demosite = "https://hugo-theme-puppet.netlify.app/"

tags = ["Blog", "Responsive", "Light"]
features = ["responsive", "comments", "sidebar", "search"]
min_version = "0.101.0"

[author]
  name = "roninro"
  homepage = "https://github.com/roninro"

# If porting an existing theme
[original]
  name = "huxblog"
  homepage = "https://github.com/Huxpro/huxpro.github.io"