name: CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - astro-papers/main

jobs:
  build:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm install --frozen-lockfile

      # - name: "🔎 Lint code"
      #   run: pnpm run lint

      # - name: "📝 Checking code format"
      #   run: pnpm run format:check

      - name: "🚀 Build the project"
        run: pnpm run build
        env:
          PUBLIC_GOOGLE_SITE_VERIFICATION: ${{ secrets.PUBLIC_GOOGLE_SITE_VERIFICATION }}
