name: Build and deploy Hexo blog
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Clean Hexo files
        run: |
          hexo clean

      - name: Generate Hexo files
        run: |
          hexo generate

      - name: Deploy Hexo blog
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: master
          commit-message: "GitHub Actions auto deploy"
          folder: ./public
          git-config-email: honmonoh@gmail.com
          token: ${{ secrets.ACCESS_TOKEN }}
