name: Build and deploy Hexo blog
on:
  workflow_dispatch:
  push:
    branches: [ source ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm dependencies
        run: |
          npm install hexo-cli -g
          npm ci

      - name: Clean and generate Hexo files
        run: |
          hexo clean
          hexo generate

      - name: Deploy Hexo blog
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: master
          commit-message: "GitHub Actions auto deploy"
          folder: ./public
          git-config-email: honmonoh@gmail.com
